### PR TITLE
fix: update the text style to prevent hiding text

### PR DESCRIPTION
**Pull request by seyedmostafahasani**
@WrathChaos Hey man,
This [issue](https://github.com/WrathChaos/react-native-bouncy-checkbox/issues/52) will be fixed with this PR.

### CODE REVIEW

**Comment by seyedmostafahasani** [comment]
I think we can fix this issue with this [(PR)](https://github.com/WrathChaos/react-native-bouncy-checkbox/issues/52)

**Comment by WrathChaos** [comment]
Hello @seyedmostafahasani 

Thank you so much for the contribution, let me quickly test and merge it :)

**Review by WrathChaos — APPROVED** [review]

**Comment by WrathChaos** [comment]
New version is up and ready! Thank you for the contribution @seyedmostafahasani 

https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/4.0.1

**Comment by seyedmostafahasani** [comment]
> New version is up and ready! Thank you for the contribution @seyedmostafahasani
> 
> https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/4.0.1

No problem @WrathChaos.

**Comment by seyedmostafahasani** [comment]
> > New version is up and ready! Thank you for the contribution @seyedmostafahasani
> > https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/4.0.1
> 
>Oh sounds good! No problem @WrathChaos.

**Pull request merged**
